services: 
  - docker

before_install:
  - docker build -t jinseal/project6-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true jinseal/project6-test npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pay-calculator"
  env: "PayCalculator"
  bucket-name: "elasticbeanstalk-us-east-2-432187221680"
  bucket-path: "pay-calculator"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY