sudo: required
services: 
  - docker

before_install:
  - docker build -t jinseal/project6-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true jinseal/project6-test npm run test -- --coverage
